version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: learn-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpwd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
