version: '3'

services:
  db2:
    image: ibmcom/db2:latest
    container_name: learn-db2
    restart: always
    privileged: true
    ports:
      - "50000:50000"
    volumes:
      - ./db2_data:/database
    environment:
      LICENSE: accept
      DBNAME: testdb
      DB2INST1_PASSWORD: root
